// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATLdRMFbIBbDkN9lVcCI8JE_kmVL97vCg',
    appId: '1:361681165354:web:f5a3c594af87846ecb3753',
    messagingSenderId: '361681165354',
    projectId: 'ai-weather632002',
    authDomain: 'ai-weather632002.firebaseapp.com',
    storageBucket: 'ai-weather632002.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC64rye2OwsQaYksWWRV-Bzs5bVRk0xJ3s',
    appId: '1:361681165354:android:e17713107b3ac6dacb3753',
    messagingSenderId: '361681165354',
    projectId: 'ai-weather632002',
    storageBucket: 'ai-weather632002.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTSBoOjrrGn-6bqLLUPWdIgzHjfHGyOVM',
    appId: '1:361681165354:ios:f6ddddb4a36831d2cb3753',
    messagingSenderId: '361681165354',
    projectId: 'ai-weather632002',
    storageBucket: 'ai-weather632002.firebasestorage.app',
    iosBundleId: 'com.example.aiWeather',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTSBoOjrrGn-6bqLLUPWdIgzHjfHGyOVM',
    appId: '1:361681165354:ios:f6ddddb4a36831d2cb3753',
    messagingSenderId: '361681165354',
    projectId: 'ai-weather632002',
    storageBucket: 'ai-weather632002.firebasestorage.app',
    iosBundleId: 'com.example.aiWeather',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATLdRMFbIBbDkN9lVcCI8JE_kmVL97vCg',
    appId: '1:361681165354:web:4ea8c8fafc572228cb3753',
    messagingSenderId: '361681165354',
    projectId: 'ai-weather632002',
    authDomain: 'ai-weather632002.firebaseapp.com',
    storageBucket: 'ai-weather632002.firebasestorage.app',
  );
}
